-- MySQL Script generated by MySQL Workbench
-- Fri Sep 16 15:15:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tallercalidad
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tallercalidad` ;

-- -----------------------------------------------------
-- Schema tallercalidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tallercalidad` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tallercalidad` ;

-- -----------------------------------------------------
-- Table `tallercalidad`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallercalidad`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account_maxquantity` VARCHAR(100) NOT NULL,
  `account_row_2` VARCHAR(45) NOT NULL,
  `account_foreigncity_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`account_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tallercalidad`.`auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallercalidad`.`auth` (
  `auth_id` INT NOT NULL,
  `auth_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auth_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tallercalidad`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallercalidad`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tallercalidad`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tallercalidad`.`user` (
  `user_id` INT NOT NULL,
  `user_identification` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `user_lastname` VARCHAR(100) NOT NULL,
  `user_gmail` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `role_role_id` INT NOT NULL,
  `auth_auth_id` INT NOT NULL,
  `account_account_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `role_role_id`, `auth_auth_id`, `account_account_id`),
  INDEX `fk_user_role_idx` (`role_role_id` ASC) VISIBLE,
  INDEX `fk_user_auth1_idx` (`auth_auth_id` ASC) VISIBLE,
  INDEX `fk_user_account1_idx` (`account_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_role_id`)
    REFERENCES `tallercalidad`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_auth1`
    FOREIGN KEY (`auth_auth_id`)
    REFERENCES `tallercalidad`.`auth` (`auth_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_account_id`)
    REFERENCES `tallercalidad`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
